version: "3"
services:
  airflow: &airflow
    build: .
    env_file: .env
    volumes:
      - .:/data_lake
    depends_on:
      - postgres
      - redis
  airflow_initdb:
    <<: *airflow
    command: airflow initdb
  airflow_webserver:
    <<: *airflow
    command: airflow webserver
    ports:
      - "8080:8080"
    restart: on-failure
  airflow_scheduler:
    <<: *airflow
    command: airflow scheduler
    restart: on-failure
  airflow_worker:
    <<: *airflow
    command: airflow worker
    restart: on-failure
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: data_lake
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_lake
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    entrypoint: sh -c "mkdir -p /storage/data_lake /storage/data_lake_test & /bin/fake-gcs-server -data /storage -scheme http"
  apisprout:
    image: danielgtaylor/apisprout
    ports:
      - "8000:8000"
    volumes:
      - ./openapi.yml:/openapi.yaml
    command: /openapi.yaml --watch
