version: "3"
services:
  initdb:
    build: .
    volumes:
      - .:/data_lake
    command: airflow initdb
    depends_on:
      - postgres
      - redis
  webserver:
    build: .
    volumes:
      - .:/data_lake
    command: airflow webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - initdb
    restart: on-failure
  scheduler:
    build: .
    volumes:
      - .:/data_lake
    command: airflow scheduler
    depends_on:
      - postgres
      - redis
      - initdb
    restart: on-failure
  worker:
    build: .
    volumes:
      - .:/data_lake
    command: airflow worker
    depends_on:
      - postgres
      - redis
      - initdb
    restart: on-failure
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: data_lake
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_lake
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    entrypoint: sh -c "mkdir -p /storage/data_lake /storage/data_lake_test & /bin/fake-gcs-server -data /storage -scheme http"
  apisprout:
    image: danielgtaylor/apisprout
    ports:
      - "8000:8000"
    volumes:
      - ./openapi.yml:/openapi.yaml
    command: /openapi.yaml --watch
