apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: fake-gcs-server
  name: fake-gcs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fake-gcs-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: fake-gcs-server
    spec:
      containers:
      - command:
        - sh
        - -c
        - mkdir -p /storage/data_lake /storage/data_lake_test & /bin/fake-gcs-server
          -data /storage -scheme http
        image: fsouza/fake-gcs-server
        imagePullPolicy: ""
        name: fake-gcs-server
        ports:
        - containerPort: 4443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
