apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisprout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisprout
  template:
    metadata:
      labels:
        app: apisprout
    spec:
      containers:
      - image: danielgtaylor/apisprout
        name: apisprout
        ports:
        - containerPort: 8000
  # volumes:
  #   # ConfigMapのvolume定義
  #   - name: config-volume
  #     configMap:
  #       # 作ったConfigMapのname
  #       name: example-config
