apiVersion: v1
kind: Deployment
metadata:
  name: apisprout
  namespace: data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisprout
  template:
    metadata:
      labels:
        app: apisprout
    spec:
      containers:
      - image: danielgtaylor/apisprout
        name: apisprout
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8000
        command:
        - apisprout
        - /etc/config/openapi.yml
      volumes:
      - name: config-volume
        configMap:
          name: data-lake-cm
          items:
          - key: openapi.yml
            path: openapi.yml
---
apiVersion: v1
kind: Service
metadata:
  name: apisprout
  namespace: data-lake
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: apisprout
