apiVersion: v1
kind: ConfigMap
metadata:
  name: data-lake
  namespace: data-lake
data:
  openapi.yml: |
    {{ openapi | indent(width=4, indentfirst=False) }}
  airflow.cfg: |
    {{ airflow | indent(width=4, indentfirst=False) }}
  unittests.cfg: |
    {{ unittests | indent(width=4, indentfirst=False) }}
  # GCS_DEFAULT_BUCKET: data_lake_test
  gcs_default_bucket: data_lake_test
  # GCS_EXTERNAL_URL: http://fake-gcs-server:4443
  gcs_external_url: http://fake-gcs-server:4443
  # GCS_PUBLIC_HOST: http://storage.gcs.fake-gcs-server.nip.io:4443
  gcs_public_host: http://storage.gcs.fake-gcs-server.nip.io:4443
  # TWITTER_ENDPOINT: http://apisprout:8000
  twitter_endpoint: http://apisprout:8000
  # TWITTER_ACCESS_KEY: data_lake
  twitter_access_key: data_lake
  # TWITTER_SECRET_KEY: password
  twitter_secret_key: password
