apiVersion: v1
kind: ConfigMap
metadata:
  name: data-lake
  namespace: data-lake
data:
  openapi.yml: |
    {{ openapi | indent(width=4, indentfirst=False) }}
  airflow.cfg: |
    {{ airflow | indent(width=4, indentfirst=False) }}
  unittests.cfg: |
    {{ unittests | indent(width=4, indentfirst=False) }}
