apiVersion: v1
kind: Namespace
metadata:
  name: data-lake
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisprout
  namespace: data-lake
data:
  openapi.yml: |
    {{ openapi|indent(4, False) }}
  airflow.cfg: |
    {{ airflow|indent(4, False) }}
