apiVersion: batch/v1
kind: Job
metadata:
  name: initdb
  namespace: data-lake
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      containers:
      - image: data_lake_airflow_initdb
        imagePullPolicy: Never
        name: initdb
        volumeMounts:
        - name: config-volume
          mountPath: /etc/airflow
        command:
        - airflow
        - initdb
      volumes:
      - name: config-volume
        configMap:
          name: data-lake-cm
          items:
          - key: airflow.cfg
            path: airflow.cfg
          - key: unittests.cfg
            path: unittests.cfg
      restartPolicy: Never
