apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:11.1
        name: postgres
        env:
        - name: POSTGRES_DB
          value: data_lake
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: data_lake
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: data-lake
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
