apiVersion: v1
kind: Deployment
metadata:
  name: webserver
  namespace: data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: data_lake_airflow_webserver
        name: webserver
        env:
        - name: GCS_DEFAULT_BUCKET
          valueFrom:
            configMapKeyRef:
              name:
              key:
        - name: GCS_EXTERNAL_URL
          valueFrom:
            configMapKeyRef:
              name:
              key:
        - name: GCS_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              name:
              key:
        - name: TWITTER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name:
              key:
        - name: TWITTER_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name:
              key:
        - name: TWITTER_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name:
              key:
        command:
        - airflow
        - webserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: data-lake
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webserver
