- hosts: localhost
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/k8s_module.html
  # kubectl create cm apisprout --from-file=../../openapi.yml --dry-run -o yaml | kubectl apply -f -
  - name: Create the postgres resources
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/postgres.yml"
  - name: Create the redis resources
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/redis.yml"
  # - name: Create the fake-gcs-server resources
  #   k8s:
  #     state: present
  #     src: "{{ playbook_dir }}/../k8s/fake-gcs-server.yml"
  # - name: Create the apisprout resources
  #   k8s:
  #     state: present
  #     src: "{{ playbook_dir }}/../k8s/fake-gcs-server.yml"
