- hosts: localhost
  debugger: on_failed
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/k8s_module.html
  # kubectl create cm apisprout --from-file=../../openapi.yml --dry-run -o yaml | kubectl apply -f -
  - name: Create the data-lake namespace
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/namespace.yml"
  - name: Create the data-lake configmap
    k8s:
      state: present
      definition: "{{ lookup('template', playbook_dir + '/../k8s/config.j2.yml') }}"
    vars:
      openapi: "{{ lookup('file', playbook_dir + '/../../openapi.yml') }}"
      airflow: "{{ lookup('file', playbook_dir + '/../../airflow.cfg') }}"
  - name: Create the data-lake middlewares workloads
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/{{ item }}.yml"
    with_items:
    - postgres
    - redis
    - fake-gcs-server
    - apisprout
  - name: Create the data-lake initdb workloads
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/initdb.yml"
