- hosts: localhost
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/k8s_module.html
  - name: Create the postgres deployment
    k8s:
      state: present
      src: "{{ playbook_dir }}/../k8s/postgres.yml"
